version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.7.2
  heroku: circleci/heroku@2.0

jobs:
  # build:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: npm
  #     - run: |
  #         echo "Installing dependencies..."
  #         npm install
  # test:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: npm
  #     - run: |
  #         echo "Running tests..."
  #         npm run test
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a dex-su-devops
            heroku container:push web -a dex-su-devops
            heroku container:release web -a dex-su-devops

workflows:
  simple_workflow:
    jobs:
      # - build
      # - test:
      #     requires:
      #       - build
      - deploy