version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.7.2
  heroku: circleci/heroku@2.0

jobs:
  build:
    # 1st way to use docker container in circleci
    docker:
      # specifying which image to use
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    # 2nd way to use docker container in circleci
    # refer to documentation on how to specify which image to use
    # e.g. - image: cimg/node:16.10
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: dexsjw/publish-assignment
      - docker/push:
          image: dexsjw/publish-assignment
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a dex-su-devops
            heroku container:push web -a dex-su-devops
            heroku container:release web -a dex-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish